version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: llm_server_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/redis
    command: redis-server --appendonly yes

  # Redis Web管理界面 - 使用更稳定的phpRedisAdmin
  redis-admin:
    image: erikdubbelboer/phpredisadmin:latest
    container_name: redis_admin
    ports:
      - "8081:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: