version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: llm_server_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/redis
    command: redis-server --appendonly yes

  # 可选：Redis管理界面
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data: